base_url = "https://teina.es"
title = "Teína"
description = "Teína, banda de indie pop-rock con intensidad y personalidad. Versiones reinterpretadas del indie nacional e internacional y canciones propias."
default_language = "es"
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]
generate_sitemap = true

[extra]
author = "Teína"
keywords = "Teína, teina, teina rock, teina banda, banda teina, teina murcia, teina indie, teina música, grupo teina, teina españa, banda indie murcia, grupo rock calasparra, música indie española, rock alternativo murcia, pop rock español, indie español, grupo musical, versiones, conciertos, eventos, festivales"

[languages.en]
title = "Teína"
description = "Teina, indie pop-rock band with intensity and personality. Reinterpreted covers of national and international indie and original songs."
