base_url = "https://teina.es"
title = "Teína"
description = "Banda de indie pop rock de Calasparra, Murcia"
default_language = "es"
compile_sass = true
build_search_index = false
generate_feeds = false

[extra]
